name: Live Stream HLS to YouTube

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Start Live Streaming from HLS
      env:
        CCTV_URL: ${{ secrets.HTTP_URL }}
        STREAM_KEY: ${{ secrets.YOUTUBE_STREAM_KEY }}
      run: |
        ffmpeg -re \
        -protocol_whitelist file,http,https,tcp,tls,crypto \
        -i "$CCTV_URL" \
        -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100 \
        -c:v copy \
        -c:a aac -b:a 128k \
        -map 0:v:0 -map 1:a:0 \
        -bsf:a aac_adtstoasc \
        -flags +global_header \
        -f flv "rtmp://a.rtmp.youtube.com/live2"
